services:
  - type: web
    name: zkss
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "server:app"
    envVars:
      - key: SHEET_URL
        value: https://script.google.com/macros/s/AKfycbyRcicjvznCOUq4ZVrLquGf2Zy9E0jqJjLpy_uaEw9nCjlCLhTpzTvgSKK_M9TGjXDA/exec
